fichiers :
	./webpage.py
	cp chronologie.md synthese.md algorithmique.md bd.md prog.md systemes.md ../docs/Cours/

push :
	git add ../docs/Cours/chronologie.md
	git add ../docs/Cours/synthese.md
	git add ../docs/Cours/algorithmique.md
	git add ../docs/Cours/bd.md 
	git add ../docs/Cours/prog.md 
	git add ../docs/Cours/systemes.md
	git commit -m "maj cours"
	git push
