fichiers :
	./webpage.py
	cp chronologie.md synthese.md algorithmique.md bd.md prog.md systemes.md ../docs/Cours/

push :
	cd ../docs/Cours
	git add chronologie.md synthese.md algorithmique.md bd.md prog.md systemes.md ../docs/Cours/
	git commit -m "maj cours"
	git push
	cd -
